volumes:
  db-product-data:
  db-currency-data:
  db-user-data:
  db-order-data:

services:

  # -------------------------------
  discovery-service:
    image: discovery-service:latest
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    
  # -------------------------------
  config-service:
    image: config-service:latest
    build:
      context: ./config-service
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
  
  # -------------------------------
  greeting-service:
    image: greeting-service:latest
    build:
      context: ./greeting-service
    depends_on:
      - discovery-service
      - config-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888

  # -------------------------------
  db-currency:
    image: postgres:16
    environment:
      POSTGRES_DB: db_currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-currency-data:/var/lib/postgresql/data
      
  currency-service:
    image: currency-service:latest
    build:
      context: ./currency-service
    depends_on:
      - discovery-service
      - db-currency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-currency:5432/db_currency
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    
  # -------------------------------
  db-product:
    image: postgres:16
    environment:
      POSTGRES_DB: db_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-product-data:/var/lib/postgresql/data
    
  product-service:
    image: product-service:latest
    build:
      context: ./product-service
    depends_on:
      - discovery-service
      - db-product
      - currency-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-product:5432/db_product
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
  # -------------------------------
  db-user:
    image: postgres:16
    environment:
      POSTGRES_DB: db_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-user-data:/var/lib/postgresql/data
    
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
    depends_on:
      - discovery-service
      - db-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-user:5432/db_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    
  # -------------------------------
  db-order:
    image: postgres:16
    environment:
      POSTGRES_DB: db_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-order-data:/var/lib/postgresql/data
    
  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    depends_on:
      - discovery-service
      - db-order
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-order:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    
  # -------------------------------
  gateway-service:
    image: gateway-service:latest
    build:
      context: ./gateway-service
    ports:
      - "8765:8765"
    depends_on:
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
    
# -------------------------------
